[package]
name = "sd-photo-uploader"
version = "0.1.0"
authors = ["Bjørn Arnholtz <bjorn.arnholtz@gmail.com>"]
edition = "2018"

[dependencies]
open = "1.3.2"
hyper = "0.12.34"
futures = "0.1.28"
tokio = "0.1.22"
clap = "2.33.0"
