[package]
name = "sd-photo-uploader"
version = "0.1.0"
authors = ["Bjørn Arnholtz <bjorn.arnholtz@gmail.com>"]
edition = "2018"

[dependencies]
open = "1.3.2"
hyper = "0.12"
clap = "2.33.0"
url = "2.1.0"
futures = "0.1.29"
tokio = "0.1.22"
percent-encoding = "2.1.0"

[profile.release]
opt-level = 'z'
codegen-units = 1
panic = 'abort'
lto = true
